program: train-toy
project: sparse-generalization
method: bayes
metric: 
  name: train_loss
  goal: minimize


parameters:
  model.l1_weight:
    distribution: uniform
    min: 0.0
    max: 1.0

command:
  - ${env}
  - uv
  - run
  - ${program}
  - model=basic-transformer